Repository leffe2/suburi, pull requests merged in 2020-03, with the labels that each got.

#85 【kiso】【EmbedC】ビット数の演算
  kiso/EmbedC/bit_num.c
  kiso/EmbedC/on_bit_num.c
  kiso/EmbedC/on_bit_num2.c
Labels: 効率のよい組込みC言語プログラミング

#86 【kiso】【EmbedC】パリティの演算
  kiso/EmbedC/get_parity.c
  kiso/EmbedC/get_parity2.c
  kiso/EmbedC/get_parity3.c
Labels: 効率のよい組込みC言語プログラミング

#87 【Proj】構造化プログラミングサンプルコード
  Proj/DrvApi/Motor.h
  Proj/DrvApi/Sensor.h
  Proj/InputCtrl/Course.c
  Proj/InputCtrl/Course.h
  Proj/InputCtrl/Road.c
  Proj/InputCtrl/Road.h
  Proj/NaviCtrl/Navi.c
  Proj/NaviCtrl/Navi.h
  Proj/OutputCtrl/Drive.c
  Proj/OutputCtrl/Drive.h
  Proj/RoboApp/Trace.c
  Proj/RoboApp/Trace.h
  Proj/SysBoot/SysCtrl.c
  Proj/SysBoot/SysCtrl.h
Labels: 組込みソフトウェア開発のための構造化プログラミング

#88 【knowhow】.virmrc設定変更
  knowhow/vim/.vimrc
Labels: vim

#89 【knowhow】.vimrc設定変更
  knowhow/vim/.vimrc
Labels: vim

#90 【Proj】構造化プログラミングサンプルコード仕様変更
  Proj/Shopping/Middleware/Trace.c
  Proj/Shopping/Middleware/Trace.h
  Proj/Shopping/RoboApp/DrivingRobot.c
  Proj/Shopping/RoboApp/DrivingRobot.h
  Proj/Shopping/RoboApp/Marker.c
  Proj/Shopping/RoboApp/Marker.h
  Proj/Shopping/RoboApp/Shopping.c
  Proj/Shopping/RoboApp/Shopping.h
  Proj/Trace_Base/DrvApi/Motor.h
  Proj/Trace_Base/DrvApi/Sensor.h
  Proj/Trace_Base/InputCtrl/Course.c
  Proj/Trace_Base/InputCtrl/Course.h
  Proj/Trace_Base/InputCtrl/Road.c
  Proj/Trace_Base/InputCtrl/Road.h
  Proj/Trace_Base/NaviCtrl/Navi.c
  Proj/Trace_Base/NaviCtrl/Navi.h
  Proj/Trace_Base/OutputCtrl/Drive.c
  Proj/Trace_Base/OutputCtrl/Drive.h
  Proj/Trace_Base/RoboApp/Trace.c
  Proj/Trace_Base/RoboApp/Trace.h
  Proj/Trace_Base/SysBoot/SysCtrl.c
  Proj/Trace_Base/SysBoot/SysCtrl.h
Labels: 組込みソフトウェア開発のための構造化プログラミング

#96 【kiso】【postit】C言語の珍しい構文
  kiso/postit/bitfield.c
  kiso/postit/trickyc.c
Labels: メモ帳

#97 【kiso】【postit】 関数ポインタ基礎1
  kiso/postit/funcpointer.c
Labels: メモ帳

#98 【kiso】【postit】関数ポインタ基礎2 関数ポインタのキャスト
  kiso/postit/funcpointer2.c
Labels: メモ帳

#99 【knowhow】.vimrc設定変更
  knowhow/vim/.vimrc
Labels: vim

#105 【Proj】関数とポインタ 引数が正しくないときの処理
  Proj/CheckArg.c
Labels: 組込みソフトウェア開発のための構造化プログラミング

#106 【Proj】いらないディレクトリの整理
  Proj/DrvApi/Motor.h
  Proj/DrvApi/Sensor.h
  Proj/InputCtrl/Course.c
  Proj/InputCtrl/Course.h
  Proj/InputCtrl/Road.c
  Proj/InputCtrl/Road.h
  Proj/NaviCtrl/Navi.c
  Proj/NaviCtrl/Navi.h
  Proj/OutputCtrl/Drive.c
  Proj/OutputCtrl/Drive.h
  Proj/RoboApp/Trace.c
  Proj/RoboApp/Trace.h
  Proj/SysBoot/SysCtrl.c
  Proj/SysBoot/SysCtrl.h
Labels: 組込みソフトウェア開発のための構造化プログラミング

#107 【Proj】ポインタと配列と関数
  Proj/resetElements.c
Labels: 組込みソフトウェア開発のための構造化プログラミング

#108 【Proj】予防的プログラミングとNULL
  Proj/nullCheck.c
Labels: 組込みソフトウェア開発のための構造化プログラミング

#109 【compression】ランレングス符号化A
  compression/list1-1.c
  knowhow/vim/.vimrc
Labels: 圧縮処理プログラミング

#110 【compression】ランレングス符号化B
  compression/list1-2.c
Labels: 圧縮処理プログラミング

#111 【compression】ランレングス符号化 C
  compression/list1-3.c
Labels: 圧縮処理プログラミング

#112 【compression】ワイル符号化
  compression/list1-4.c
Labels: 圧縮処理プログラミング

#113 【compression】ランレングス符号E PackBits
  compression/list1-5.c
Labels: 圧縮処理プログラミング

#114 【compression】ランレングス符号E PackBits2
  compression/list1-6.c
Labels: 圧縮処理プログラミング

#115 【knowhow】.vimrc設定変更
  knowhow/vim/.vimrc
Labels: vim

#116 【compression】ランレングス符号化Aを伸長
  compression/list1-7.c
Labels: 圧縮処理プログラミング

#117 【compression】ランレングス符号化Bを伸長
  compression/list1-8.c
Labels: 圧縮処理プログラミング

#118 【compression】ランレングス符号化Cを伸長
  compression/list1-9.c
Labels: 圧縮処理プログラミング

#119 【compression】ランレングス符号D ワイル符号化を伸張
  compression/list1-10.c
Labels: 圧縮処理プログラミング

#120 【compression】ランレングス符号E PackBitsを伸張
  compression/list1-11.c
Labels: 圧縮処理プログラミング

#121 【compression】ランレングス符号E PackBits2を伸張
  compression/list1-12.c
Labels: 圧縮処理プログラミング

#122 【compression】CHAPTER1のフォルダを作成
  compression/chapter1/list1-1.c
  compression/chapter1/list1-10.c
  compression/chapter1/list1-11.c
  compression/chapter1/list1-12.c
  compression/chapter1/list1-2.c
  compression/chapter1/list1-3.c
  compression/chapter1/list1-4.c
  compression/chapter1/list1-5.c
  compression/chapter1/list1-6.c
  compression/chapter1/list1-7.c
  compression/chapter1/list1-8.c
  compression/chapter1/list1-9.c
Labels: 圧縮処理プログラミング

#123 【compression】画像処理のための基本プログラム
  compression/chapter2/image.c
  compression/chapter2/image.h
Labels: 圧縮処理プログラミング

#124 【compression】BMPの入出力プログラム
  compression/chapter2/bmp.c
Labels: 圧縮処理プログラミング

#125 【compression】BMPの入出力プログラムの修正
  compression/chapter2/Makefile
  compression/chapter2/bmp.c
  compression/chapter2/image.c
  compression/chapter2/image.h
  compression/list1-1.c
  compression/list1-10.c
  compression/list1-11.c
  compression/list1-12.c
  compression/list1-2.c
  compression/list1-3.c
  compression/list1-4.c
  compression/list1-5.c
  compression/list1-6.c
  compression/list1-7.c
  compression/list1-8.c
  compression/list1-9.c
Labels: 圧縮処理プログラミング

#126 【compression】BMPの入出力プログラムがセグ落ちするバグを修正
  compression/chapter2/bmp.c
  compression/chapter2/image.c
  compression/chapter2/image.h
  compression/chapter2/out.bmp
Labels: 圧縮処理プログラミング

#127 【compression】圧縮時の処理順序(走査方法)
  compression/chapter2/list2-10.c
  compression/chapter2/list2-11.c
Labels: 圧縮処理プログラミング

#128 【compression】横方向に走査
  compression/chapter2/list2-13.c
Labels: 圧縮処理プログラミング

#129 【compression】縦方向に走査
  compression/chapter2/list2-14.c
Labels: 圧縮処理プログラミング

#130 【compression】ジグザグに走査
  compression/chapter2/list2-15.c
Labels: 圧縮処理プログラミング

#131 【compression】左右に走査
  compression/chapter2/list2-16.c
Labels: 圧縮処理プログラミング

#132 【compression】ブロックに分けて走査
  compression/chapter2/list2-17.c
Labels: 圧縮処理プログラミング

#133 【knowhow】.vimrcの設定変更
  knowhow/vim/.vimrc
Labels: 圧縮処理プログラミング

#134 【compression】BMPファイルを圧縮する
  compression/chapter2/list2-18.c
Labels: 圧縮処理プログラミング

#135 【knowhow】.vimrcの設定変更
  knowhow/vim/.vimrc
Labels: vim
